name: Build Apk
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Sign with debug key
      run: |
        sed -i "19i signingConfig signingConfigs.debug" ./app/build.gradle
        curl -so- https://raw.githubusercontent.com/artem-zinnatullin/RxJavaProGuardRules/master/rxjava-proguard-rules/proguard-rules.txt | tee -a ./app/proguard-rules.pro
        cat ./app/proguard-rules.pro

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Build debug APK
      run: ./gradlew assembleDebug --stacktrace

    - name: Get App Version Name
      id: version
      run: |
        VERSION_NAME=$(grep versionName app/build.gradle | sed -n 's/.*versionName \"\([0-9.]*\)\".*/\1/p')
        echo "APP_VERSION=$VERSION_NAME" >> $GITHUB_ENV

    - name: Rename APK
      run: mv app/build/outputs/apk/debug/app-debug.apk game-unlocker-v${{ env.APP_VERSION }}.apk

    - name: Upload APK as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Game Unlocker
        path: game-unlocker-v${{ env.APP_VERSION }}.apk

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.1.0
      with:
        tag_name: ${{ env.APP_VERSION }}
        release_name: ${{ env.APP_VERSION }}
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload APK to Release
      uses: actions/upload-release-asset@v4
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: game-unlocker-v${{ env.APP_VERSION }}.apk
        asset_name: game-unlocker-v${{ env.APP_VERSION }}.apk
        asset_content_type: application/vnd.android.package-archive
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
